services:
  forsaj-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      PORT: "5000"
      WEB_DATA_DIR: "/app/data/web-data"
      ADMIN_PUBLIC_DIR: "/app/data/web-data"
      UPLOAD_DIR: "/app/data/uploads"
      MYSQL_HOST: "forsaj-db"
      MYSQL_USER: "forsaj_user"
      MYSQL_PASSWORD: "forsaj_password_99"
      MYSQL_DATABASE: "forsaj_admin"
    volumes:
      - /datastore/forsaj/data:/app/data
    depends_on:
      forsaj-db:
        condition: service_healthy
    networks:
      - edge
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://127.0.0.1:5000/api/health >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 8
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj-api.rule=Host(`forsaj.octotech.az`) && (PathPrefix(`/api`) || PathPrefix(`/uploads`))'
      - 'traefik.http.routers.forsaj-api.entrypoints=web,websecure'
      - 'traefik.http.routers.forsaj-api.tls=true'
      - 'traefik.http.routers.forsaj-api.priority=1500'
      - 'traefik.http.services.forsaj-api.loadbalancer.server.port=5000'

  forsaj-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    depends_on:
      forsaj-backend:
        condition: service_healthy
    networks:
      - edge
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://127.0.0.1/ >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 8
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj.rule=Host(`forsaj.octotech.az`)'
      - 'traefik.http.routers.forsaj.entrypoints=web,websecure'
      - 'traefik.http.routers.forsaj.tls=true'
      - 'traefik.http.routers.forsaj.priority=500'
      - 'traefik.http.services.forsaj.loadbalancer.server.port=80'

  forsaj-admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    restart: unless-stopped
    depends_on:
      forsaj-backend:
        condition: service_healthy
    networks:
      - edge
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://127.0.0.1/admin/ >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 8
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj-admin.rule=Host(`forsaj.octotech.az`) && PathPrefix(`/admin`)'
      - 'traefik.http.routers.forsaj-admin.entrypoints=web,websecure'
      - 'traefik.http.routers.forsaj-admin.tls=true'
      - 'traefik.http.routers.forsaj-admin.priority=1000'
      - 'traefik.http.services.forsaj-admin.loadbalancer.server.port=80'

  forsaj-db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "forsaj_root_secure_2026"
      MYSQL_DATABASE: "forsaj_admin"
      MYSQL_USER: "forsaj_user"
      MYSQL_PASSWORD: "forsaj_password_99"
    volumes:
      - /datastore/forsaj/mysql:/var/lib/mysql
    networks:
      - edge
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.forsaj-db-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.forsaj-db-tcp.entrypoints=mysql"
      - "traefik.tcp.services.forsaj-db-tcp.loadbalancer.server.port=3306"

  forsaj-db-admin:
    build:
      context: .
      dockerfile: Dockerfile.phpmyadmin
    restart: unless-stopped
    depends_on:
      forsaj-db:
        condition: service_healthy
    networks:
      - edge
    environment:
      PMA_HOST: "forsaj-db"
      PMA_ABSOLUTE_URI: "https://forsaj.octotech.az/dbadmin/"
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.forsaj-dbadmin.rule=Host(`forsaj.octotech.az`) && PathPrefix(`/dbadmin`)'
      - 'traefik.http.routers.forsaj-dbadmin.entrypoints=web,websecure'
      - 'traefik.http.routers.forsaj-dbadmin.tls=true'
      - 'traefik.http.routers.forsaj-dbadmin.priority=3000'
      - 'traefik.http.routers.forsaj-dbadmin.middlewares=forsaj-dbadmin-strip'
      - 'traefik.http.middlewares.forsaj-dbadmin-strip.stripprefix.prefixes=/dbadmin'
      - 'traefik.http.services.forsaj-dbadmin.loadbalancer.server.port=80'

networks:
  edge:
    external: true
